# Generated by Django 5.0.1 on 2024-05-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=30)),
                ('PORT', models.CharField(max_length=30)),
                ('ADD_DATE', models.DateTimeField(auto_now_add=True)),
                ('DEL_DATE', models.DateTimeField(blank=True, null=True)),
                ('LAST_CONN_DATE', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
